# Generated by Django 5.2 on 2025-05-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqitem',
            name='created_by',
        ),
    ]
