# Generated by Django 5.2 on 2025-05-24 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faqcategory_author_faqitem_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Название должно содержать минимум 3 символа'), django.core.validators.MaxLengthValidator(100, message='Максимальная длина названия - 100 символов'), django.core.validators.RegexValidator(message='Допустимы буквы, цифры, пробелы, дефисы и подчеркивания', regex='^[а-яА-ЯёЁa-zA-Z0-9\\s\\-_]+$')], verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000, message='Максимальное значение порядка - 1000')], verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, message='Ответ должен содержать минимум 20 символов'), django.core.validators.MaxLengthValidator(5000, message='Максимальная длина ответа - 5000 символов')], verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='order',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000, message='Максимальное значение порядка - 1000')], verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='question',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10, message='Вопрос должен содержать минимум 10 символов'), django.core.validators.RegexValidator(message='Допустимы буквы, цифры и основные знаки препинания', regex='^[а-яА-ЯёЁa-zA-Z0-9\\s\\-\\?\\.!,]+$')], verbose_name='Вопрос'),
        ),
    ]
