# Generated by Django 5.2 on 2025-05-24 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_alter_faqcategory_name_alter_faqcategory_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Ответ должен содержать минимум 20 символов'), django.core.validators.MaxLengthValidator(5000, message='Максимальная длина ответа - 5000 символов')], verbose_name='Ответ'),
        ),
    ]
