# Generated by Django 5.2 on 2025-04-19 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'.", regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
