# Generated by Django 5.2 on 2025-05-21 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'.", regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
