# Generated by Django 5.2 on 2025-05-24 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Комментарий должен содержать минимум 10 символов'), django.core.validators.MaxLengthValidator(1000, message='Максимальная длина комментария - 1000 символов')], verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MaxLengthValidator(254, message='Максимальная длина email - 254 символа')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Имя может содержать только буквы и дефисы', regex='^[а-яА-ЯёЁa-zA-Z\\s\\-]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='Фамилия может содержать только буквы и дефисы', regex='^[а-яА-ЯёЁa-zA-Z\\s\\-]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79999999999'.", regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(4, message='Логин должен содержать минимум 4 символа'), django.core.validators.MaxLengthValidator(30, message='Максимальная длина логина - 30 символов'), django.core.validators.RegexValidator(message='Логин может содержать только буквы, цифры и символы @/./+/-/_', regex='^[\\w.@+-]+\\Z')], verbose_name='Логин'),
        ),
    ]
