# Generated by Django 5.2 on 2025-04-30 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appeals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appealdocument',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appeals.appeal'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='tags',
            field=models.ManyToManyField(blank=True, to='appeals.tag', verbose_name='Теги'),
        ),
    ]
