# Generated by Django 5.2 on 2025-04-26 09:11

from django.db import migrations

def add_initial_tags(apps, schema_editor):
    Tag = apps.get_model('appeals', 'Tag')
    initial_tags = [
        "Протечка воды",
        "Засор канализации",
        "Поломка лифта",
        "Электричество",
        "Отопление",
        "Мусоропровод",
        "Крыша",
        "Подъезд",
        "Дворовая территория"
    ]
    for tag_name in initial_tags:
        Tag.objects.get_or_create(name=tag_name)

class Migration(migrations.Migration):
    dependencies = [
        ('appeals', '0002_tag_appeal_tags'),  # Укажите предыдущую миграцию
    ]

    operations = [
        migrations.RunPython(add_initial_tags),
    ]