# Generated by Django 5.2 on 2025-04-26 09:25
from django.db import migrations

def add_default_tags(apps, schema_editor):
    Tag = apps.get_model('appeals', 'Tag')
    tags = [
        "Протечка воды",
        "Засор канализации",
        "Поломка лифта",
        "Электричество",
        "Отопление"
    ]
    for name in tags:
        Tag.objects.get_or_create(name=name)

class Migration(migrations.Migration):
    dependencies = [
        ('appeals', '0003_add_initial_tags'),
    ]

    operations = [
        migrations.RunPython(add_default_tags),
    ]