# Generated by Django 5.2 on 2025-05-04 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0003_add_default_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='ФИО'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appeals.appeal')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
    ]
