# Generated by Django 5.2 on 2025-05-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0004_alter_appeal_address_alter_appeal_full_name_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл сотрудник'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='employee_status',
            field=models.CharField(choices=[('free', 'Свободное'), ('in_progress', 'В работе'), ('closed', 'Закрыто')], default='free', max_length=20, verbose_name='Статус для сотрудников'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Взято в работу'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Взял сотрудник'),
        ),
    ]
