# Generated by Django 5.2 on 2025-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0005_appeal_closed_at_appeal_closed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='feedback_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий оценки'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Оценка'),
        ),
    ]
