# Generated by Django 5.2 on 2025-05-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0006_appeal_feedback_comment_appeal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
