# Generated by Django 5.2 on 2025-05-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0011_remove_old_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='employee_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.employeestatus', verbose_name='Статус для сотрудников'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.priority', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appeals.appealstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='appealstatus',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='employeestatus',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
