# Generated by Django 5.2 on 2025-05-21 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0012_alter_appeal_employee_status_alter_appeal_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
