# Generated by Django 5.2 on 2025-05-24 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeals', '0013_appeal_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Описание должно содержать минимум 10 символов')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='ФИО может содержать только буквы, пробелы и дефисы', regex='^[а-яА-ЯёЁa-zA-Z\\s\\-]+$')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате +7XXXXXXXXXX', regex='^\\+7\\d{10}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, message='Заголовок должен содержать минимум 5 символов')], verbose_name='Заголовок'),
        ),
    ]
